/*
 * ps5_kat.h - PS5 tiling known-answer table.
 *
 * Generated by tools/ps5_oracle from Sony's AgcGpuAddress host library
 * (PS5 SDK 4.00): for each case a deterministic pseudo-random surface
 * (kat_fill / kat_seed in tools/ps5_oracle/kat_common.h) is detiled mip by
 * mip, slice by slice, with the SDK, and the concatenated output hashed
 * (FNV-1a 64). tests/test_main.cpp recomputes the same with tex_codec's
 * public API. Regenerate with `ps5_oracle kat` / `ps5_oracle samples`.
 */
#ifndef TEXC_PS5_KAT_H
#define TEXC_PS5_KAT_H

#include <stdint.h>
#include "../include/tex_codec.h"

struct ps5_kat {
    uint32_t tile_mode;
    texc_format format;
    uint32_t w, h, mips, slices;
    uint64_t surface_size;
    uint64_t hash;
};

/* Generated by tools/ps5_oracle (kat) from Sony's AgcGpuAddress host
 * library. Do not edit by hand. Each entry: tile mode, format, w, h,
 * mips, slices, surface size, FNV-1a of all mips/slices detiled. */
static const ps5_kat k_ps5_kat[] = {
    { 5, TEXC_FORMAT_BC7, 256, 256, 9, 1, 90112ull, 0x46e0c3b982249a05ull },
    { 5, TEXC_FORMAT_BC7, 512, 128, 10, 1, 98304ull, 0x8a8b7310dad06d41ull },
    { 5, TEXC_FORMAT_BC7, 128, 512, 10, 1, 94208ull, 0x89d989d36b2159f0ull },
    { 5, TEXC_FORMAT_BC1, 256, 256, 9, 1, 45056ull, 0x41d463a209bb4f27ull },
    { 5, TEXC_FORMAT_BC1, 64, 32, 7, 1, 4096ull, 0xc074b6e6600270ddull },
    { 5, TEXC_FORMAT_RGBA8, 256, 256, 9, 1, 352256ull, 0x8656261b8ef74f12ull },
    { 5, TEXC_FORMAT_RGBA8, 64, 128, 8, 1, 45056ull, 0x479f84e2e57bf7afull },
    { 5, TEXC_FORMAT_BC7, 37, 23, 6, 1, 8192ull, 0xcc9c3435e8709250ull },
    { 5, TEXC_FORMAT_BC1, 100, 60, 7, 1, 8192ull, 0x5c0900e3d6b6dcf3ull },
    { 5, TEXC_FORMAT_RGBA8, 300, 70, 9, 1, 192512ull, 0x2fb665762bcc37c0ull },
    { 5, TEXC_FORMAT_BC7, 64, 64, 7, 6, 49152ull, 0x5697d73ce368d250ull },
    { 5, TEXC_FORMAT_BC1, 32, 32, 1, 4, 16384ull, 0xfdca7eb2792263b5ull },
    { 5, TEXC_FORMAT_BC7, 1, 1, 1, 1, 4096ull, 0xa325f647173e8274ull },
    { 5, TEXC_FORMAT_BC7, 4, 4, 1, 1, 4096ull, 0x5bc70846fbf218eeull },
    { 5, TEXC_FORMAT_RGBA8, 5, 999, 10, 1, 258048ull, 0x7f4ec453994ae74aull },
    { 9, TEXC_FORMAT_BC7, 512, 512, 10, 1, 393216ull, 0x6b468dd4e5b33d64ull },
    { 9, TEXC_FORMAT_BC1, 256, 128, 9, 1, 65536ull, 0xcc52d9d6a557ee44ull },
    { 9, TEXC_FORMAT_RGBA8, 300, 70, 9, 2, 917504ull, 0xa8bc7b4881d02511ull },
    { 9, TEXC_FORMAT_BC7, 37, 23, 6, 1, 65536ull, 0x7157fcb0284b3dd6ull },
    { 1, TEXC_FORMAT_BC7, 256, 256, 9, 1, 88320ull, 0x99f4a64e3f13710cull },
    { 1, TEXC_FORMAT_BC1, 100, 60, 7, 3, 19200ull, 0x8434e8fc72135e4full },
    { 1, TEXC_FORMAT_RGBA8, 64, 64, 7, 1, 22528ull, 0x116f51a80c847eb1ull },
};

/* Real G1T PS5 textures (not committed; the test runs these only when
 * samples/ps5/textures/ is present). data_offset / data_size locate the
 * tiled surface in the file. tile_mode is the standard mode whose surface
 * size equals data_size (G1T has no tile-mode field; Koei Tecmo content
 * uses STANDARD_4KB for small textures and STANDARD_64KB for large ones),
 * which is what texc_ps5_detect_tile_mode recovers. */
struct ps5_sample_kat {
    const char *file;
    texc_format format;
    uint32_t w, h, mips;
    uint32_t tile_mode;
    uint32_t data_offset;
    uint64_t data_size;
    uint64_t hash;
};

static const ps5_sample_kat k_ps5_samples[] = {
    { "000cfaa4.g1t", TEXC_FORMAT_BC7, 256, 256, 7, 5, 56, 90112ull, 0x1d9f8eacb659661full },
    { "0a8f4727.g1t", TEXC_FORMAT_BC7, 128, 128, 6, 5, 56, 24576ull, 0x6d3980ccee655bb7ull },
    { "0a9fb934.g1t", TEXC_FORMAT_BC7, 256, 256, 7, 5, 56, 90112ull, 0x49a907bb940e2cbeull },
    { "0x28e2b560.g1t", TEXC_FORMAT_BC1, 256, 256, 5, 5, 56, 45056ull, 0xcfa3af4cf807dab2ull },
    { "0x4fff0348.g1t", TEXC_FORMAT_BC7, 64, 2048, 5, 9, 56, 983040ull, 0x47c473fedfe601f6ull },
    { "0x70f1f773.g1t", TEXC_FORMAT_BC4, 256, 128, 6, 5, 56, 24576ull, 0x2724f797e07a5d1dull },
    { "0xc2e63d48.g1t", TEXC_FORMAT_BC7, 512, 128, 6, 5, 56, 98304ull, 0x1fcd7a7622bc4f27ull },
    { "0xf773bb73.g1t", TEXC_FORMAT_BC7, 128, 512, 6, 5, 56, 94208ull, 0x0725f241934393abull },
    { "0xf7bfb555.g1t", TEXC_FORMAT_BC7, 256, 256, 7, 5, 56, 90112ull, 0x35ea2867cc0986e4ull },
    { "0xfcafccd4.g1t", TEXC_FORMAT_BC7, 256, 128, 6, 5, 56, 49152ull, 0x5ea5e427b3f67542ull },
    { "0xffb7bfa3.g1t", TEXC_FORMAT_BC7, 1024, 128, 6, 9, 56, 524288ull, 0xeee8bb3bf83d3669ull },
    { "fbff6177.g1t", TEXC_FORMAT_BC7, 128, 128, 6, 5, 56, 24576ull, 0xa3309ae96a9881daull },
};

#endif /* TEXC_PS5_KAT_H */
